version: 0.1

phases:
  build:
    commands:
      - nvm install 16.13.0
      - npm install
      - npm run webpack

artifacts:
  files:
    - index.html
    - favicon.ico
    - styles/main.css
    - images/*
    - dist/bundle.js
